# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/teja/MeshSegmentation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/teja/MeshSegmentation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/teja/MeshSegmentation/CMakeFiles /home/teja/MeshSegmentation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/teja/MeshSegmentation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named docs

# Build rule for target.
docs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 docs
.PHONY : docs

# fast build rule for target.
docs/fast:
	$(MAKE) -f CMakeFiles/docs.dir/build.make CMakeFiles/docs.dir/build
.PHONY : docs/fast

#=============================================================================
# Target rules for targets named HierarchicalFaceCluster-lib

# Build rule for target.
HierarchicalFaceCluster-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HierarchicalFaceCluster-lib
.PHONY : HierarchicalFaceCluster-lib

# fast build rule for target.
HierarchicalFaceCluster-lib/fast:
	$(MAKE) -f src/CMakeFiles/HierarchicalFaceCluster-lib.dir/build.make src/CMakeFiles/HierarchicalFaceCluster-lib.dir/build
.PHONY : HierarchicalFaceCluster-lib/fast

#=============================================================================
# Target rules for targets named HFC_test

# Build rule for target.
HFC_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HFC_test
.PHONY : HFC_test

# fast build rule for target.
HFC_test/fast:
	$(MAKE) -f test/CMakeFiles/HFC_test.dir/build.make test/CMakeFiles/HFC_test.dir/build
.PHONY : HFC_test/fast

#=============================================================================
# Target rules for targets named tinyxml2

# Build rule for target.
tinyxml2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyxml2
.PHONY : tinyxml2

# fast build rule for target.
tinyxml2/fast:
	$(MAKE) -f test/CMakeFiles/tinyxml2.dir/build.make test/CMakeFiles/tinyxml2.dir/build
.PHONY : tinyxml2/fast

#=============================================================================
# Target rules for targets named CGAL_Project

# Build rule for target.
CGAL_Project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Project
.PHONY : CGAL_Project

# fast build rule for target.
CGAL_Project/fast:
	$(MAKE) -f test/extern/CMakeFiles/CGAL_Project.dir/build.make test/extern/CMakeFiles/CGAL_Project.dir/build
.PHONY : CGAL_Project/fast

#=============================================================================
# Target rules for targets named CoMISo

# Build rule for target.
CoMISo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CoMISo
.PHONY : CoMISo

# fast build rule for target.
CoMISo/fast:
	$(MAKE) -f test/CoMISo/CMakeFiles/CoMISo.dir/build.make test/CoMISo/CMakeFiles/CoMISo.dir/build
.PHONY : CoMISo/fast

#=============================================================================
# Target rules for targets named lim

# Build rule for target.
lim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lim
.PHONY : lim

# fast build rule for target.
lim/fast:
	$(MAKE) -f test/lim/CMakeFiles/lim.dir/build.make test/lim/CMakeFiles/lim.dir/build
.PHONY : lim/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) -f test/glad/CMakeFiles/glad.dir/build.make test/glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f test/glfw/src/CMakeFiles/glfw.dir/build.make test/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named igl_stb_image

# Build rule for target.
igl_stb_image: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 igl_stb_image
.PHONY : igl_stb_image

# fast build rule for target.
igl_stb_image/fast:
	$(MAKE) -f test/stb_image/CMakeFiles/igl_stb_image.dir/build.make test/stb_image/CMakeFiles/igl_stb_image.dir/build
.PHONY : igl_stb_image/fast

#=============================================================================
# Target rules for targets named tetgen

# Build rule for target.
tetgen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tetgen
.PHONY : tetgen

# fast build rule for target.
tetgen/fast:
	$(MAKE) -f test/tetgen/CMakeFiles/tetgen.dir/build.make test/tetgen/CMakeFiles/tetgen.dir/build
.PHONY : tetgen/fast

#=============================================================================
# Target rules for targets named triangle

# Build rule for target.
triangle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangle
.PHONY : triangle

# fast build rule for target.
triangle/fast:
	$(MAKE) -f test/triangle/CMakeFiles/triangle.dir/build.make test/triangle/CMakeFiles/triangle.dir/build
.PHONY : triangle/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... docs"
	@echo "... edit_cache"
	@echo "... HierarchicalFaceCluster-lib"
	@echo "... HFC_test"
	@echo "... tinyxml2"
	@echo "... CGAL_Project"
	@echo "... CoMISo"
	@echo "... lim"
	@echo "... glad"
	@echo "... glfw"
	@echo "... igl_stb_image"
	@echo "... tetgen"
	@echo "... triangle"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

